### PR TITLE
Fix: pass command into shell in buffer mode

### PR DESCRIPTION
**Pull request by costowell**

### CODE REVIEW

**Comment by desdic** [comment]
Thanks but this will be a breaking change (Not that this is a problem) but is it because you only want a single line or do you need something the shell sources when running bash ? 

Then it might be better to expand the change a bit and make a 
1. shell_command instead of command
2. make the shell a variable and default to sh

**Comment by costowell** [comment]
The vscode tasks.json sometimes has the command and args bundled together, and it ends up looking for an executable named, for example, `echo hello`, instead of just `echo`. When using toggleterm, this does not happen because the command is passed into the shell. My thought was to keep the behavior consistent and supporting more possible configs.

In retrospect, I should have elaborated a little more haha :)

**Comment by costowell** [comment]
>     2. make the shell a variable and default to sh (or maybe vim.opt.shell)

Totally agree with this. There are some shells that have different syntax that is possibly incompatible with some commands. I think that a shell options is in order, but it should default to sh otherwise.

**Comment by desdic** [comment]
> Totally agree with this. There are some shells that have different syntax that is possibly incompatible with some commands. I think that a shell option is in order, but it should default to sh otherwise.

perfect, didn't see this one .. but if you change it to vim.opt.shell or a variable I'll merge :)

**Comment by costowell** [comment]
I opted to have a config option which defaults to `vim.o.shell`. Best of both worlds :)

**Comment by desdic** [comment]
Just testet it and its throwing an error .. does it work for you ? it seems like the config is nil

```sh
Error executing vim.schedule lua callback: Vim:E475: Invalid value for argument cmd: 'v:null' is not executable                                                           
stack traceback:                                                                                                                                                          
        [C]: in function 'jobstart'                                                                                                                                       
        /home/kgn/src/private/greyjoy.nvim/lua/greyjoy/init.lua:188: in function 'to_buffer'                                                                              
        /home/kgn/src/private/greyjoy.nvim/lua/greyjoy/init.lua:98: in function 'cb'                                                                                      
        ...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:206: in function <...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:202>                    
        [C]: in function 'wait'                                                                                                                                           
        /home/kgn/.local/share/nvim/lazy/nvim-lint/lua/lint.lua:166: in function 'cancel'                                                                                 
        /home/kgn/.local/share/nvim/lazy/nvim-lint/lua/lint.lua:254: in function 'try_lint'                                                                               
        /home/kgn/.config/nvim/lua/plugins/nvim-lint.lua:46: in function </home/kgn/.config/nvim/lua/plugins/nvim-lint.lua:45>   
```

and vim.o.shell contains `zsh` don't know if there is an option for full path (checking)

**Comment by desdic** [comment]
yes if you change
```lua
local shell_command = { config["default_shell"], "-c", commandstr }
```
to
```lua
local shell_command = { greyjoy.default_shell, "-c", commandstr }
```
then it works :)

**Comment by desdic** [comment]
Merged and thank you for the MR :)

**Pull request merged**
